logging:
  level:
    com.github.marsbits.restfbmessenger: DEBUG
management.context-path: /management
restfbmessenger:
  verify-token: the-verify-token
  access-token: the-access-token
  app-secret: the-app-secret
